#ifndef ATLANTIK_MAIN_H
#define ATLANTIK_MAIN_H

#define	ATLANTIK_VERSION 030
#define	ATLANTIK_VERSION_STRING "0.3.0 (CVS >= 20020330)"
#define ATLANTIK_VERSION_MAJOR 0
#define ATLANTIK_VERSION_MINOR 3
#define ATLANTIK_VERSION_RELEASE 0

int main(int, char *[]);

#endif
