#ifndef ATLANTIK_MAIN_H
#define ATLANTIK_MAIN_H

#define	ATLANTIK_VERSION 020
#define	ATLANTIK_VERSION_STRING "0.2.0"
#define ATLANTIK_VERSION_MAJOR 0
#define ATLANTIK_VERSION_MINOR 2
#define ATLANTIK_VERSION_RELEASE 0

int main(int, char *[]);

#endif
