#ifndef ATLANTIK_MAIN_H
#define ATLANTIK_MAIN_H

#define	ATLANTIK_VERSION 012
#define	ATLANTIK_VERSION_STRING "0.1.2 (CVS >= 20011127)"
#define ATLANTIK_VERSION_MAJOR 0
#define ATLANTIK_VERSION_MINOR 1
#define ATLANTIK_VERSION_RELEASE 2

int main(int, char *[]);

#endif
